DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products_categories CASCADE;
DROP TABLE IF EXISTS transaction_details CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;

DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS variants CASCADE;
DROP TABLE IF EXISTS sizes CASCADE;
DROP TABLE IF EXISTS methods CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS vouchers CASCADE;
DROP TABLE IF EXISTS discount CASCADE;
DROP TABLE IF EXISTS testimony CASCADE;

DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;