basePath: /
definitions:
  dto.CreateItemRequest:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
      size_id:
        type: integer
      variant_id:
        type: integer
    type: object
  dto.CreateProductRequest:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
  dto.CreateReviewProductRequest:
    properties:
      id_transaction_details:
        type: integer
      message:
        type: string
      rating:
        type: number
      user_id:
        type: string
    type: object
  dto.CreateTransactionRequest:
    properties:
      id_method:
        type: integer
      id_voucher:
        type: integer
      items:
        items:
          $ref: '#/definitions/dto.CreateItemRequest'
        type: array
      payment_method:
        type: string
      user_id:
        type: string
    type: object
  dto.ForgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.RegisterRequest:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - password
    type: object
  dto.ResetPwdRequest:
    properties:
      code:
        type: integer
      email:
        type: string
      new_password:
        type: string
    type: object
  dto.Response:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.ResponseToken:
    properties:
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  dto.UpdateUsersRequest:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
      picture:
        type: string
      role_id:
        type: integer
    type: object
  dto.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.ItemDetail:
    properties:
      product_image:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
      size:
        type: string
      subtotal:
        type: integer
      transaction_id:
        type: string
      variant:
        type: string
    type: object
  models.Product:
    properties:
      categories:
        items:
          type: string
        type: array
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
      updatedAt:
        type: string
    type: object
  models.ReviewProduct:
    properties:
      id:
        type: integer
      idTransactionDetail:
        type: integer
      message:
        type: string
      rating:
        type: number
      userId:
        type: string
    type: object
  models.Transaction:
    properties:
      address:
        type: string
      created_at:
        type: string
      full_name:
        type: string
      id:
        type: string
      items:
        items:
          $ref: '#/definitions/models.ItemDetail'
        type: array
      payment_method:
        type: string
      phone:
        type: string
      shipping:
        type: string
      status:
        type: string
      total_transaction:
        type: integer
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is a coffee shop backend API
  title: Coffee Shop API
  version: "1.0"
paths:
  /admin/users:
    get:
      description: Retrieve list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get all users
      tags:
      - Users
  /admin/users/{id}:
    delete:
      description: Delete user by UUID
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Delete user
      tags:
      - Users
    get:
      description: Retrieve a single user by UUID
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get user by ID
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: Update user data by UUID
      parameters:
      - description: User ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Update User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUsersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Update user
      tags:
      - Users
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Send OTP code to user email for password reset
      parameters:
      - description: User Email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Request forgot password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Login Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Login new user
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Register Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Register new user
      tags:
      - Authentication
  /auth/reset-password:
    patch:
      consumes:
      - application/json
      description: Reset user password using OTP code
      parameters:
      - description: Reset Password Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPwdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Reset password
      tags:
      - Auth
  /products:
    get:
      consumes:
      - application/json
      description: Retrieve all products from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a new product in database
      parameters:
      - description: Product Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create new product
      tags:
      - Products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get product by ID
      tags:
      - Products
  /recommended-product:
    get:
      consumes:
      - application/json
      description: Retrieve recommended products for landing page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get recommended products
      tags:
      - Landing
  /recommended-product/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve recommended product detail by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get recommended product by ID
      tags:
      - Landing
  /review-product:
    get:
      consumes:
      - application/json
      description: Retrieve all review products from database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ReviewProduct'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all review products
      tags:
      - ReviewProducts
    post:
      consumes:
      - application/json
      description: Create a new review product
      parameters:
      - description: Review Product Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ReviewProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create review product
      tags:
      - ReviewProducts
  /review-product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete review product by ID
      parameters:
      - description: Review Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Delete review product
      tags:
      - ReviewProducts
    get:
      consumes:
      - application/json
      description: Retrieve a single review product by its ID
      parameters:
      - description: Review Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReviewProduct'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get review product by ID
      tags:
      - ReviewProducts
  /review-products:
    post:
      consumes:
      - application/json
      description: Create a new review product
      parameters:
      - description: Review Product Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateReviewProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create review product
      tags:
      - ReviewProducts
  /reviews:
    get:
      consumes:
      - application/json
      description: Retrieve all review products for landing page
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ReviewProduct'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get all review products
      tags:
      - Landing
  /reviews/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve review product by ID
      parameters:
      - description: Review Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReviewProduct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get review product by ID
      tags:
      - Landing
  /transactions:
    get:
      consumes:
      - application/json
      description: Retrieve all transactions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all transactions
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: Create a new transaction with transaction details
      parameters:
      - description: Transaction Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Create transaction
      tags:
      - Transactions
  /transactions/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve transaction detail by UUID
      parameters:
      - description: Transaction ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get transaction by ID
      tags:
      - Transactions
swagger: "2.0"
